// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmallStructuresTakeOffs.Models;

namespace SmallStructuresTakeOffs.Migrations
{
    [DbContext(typeof(EFCoreDBcontext))]
    [Migration("20210602030453_AddingP1569_1MCatchBasin")]
    partial class AddingP1569_1MCatchBasin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmallStructuresTakeOffs.Models.C1580CB", b =>
                {
                    b.Property<int>("C1580CBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("C1580CBCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C1580CBDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("C1580CBHeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("C1580Reb4FandI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C1580Reb4Purch")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("C1580CBId");

                    b.ToTable("C1580CBs");
                });

            modelBuilder.Entity("SmallStructuresTakeOffs.Models.P1569_1M", b =>
                {
                    b.Property<int>("P1569_1MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("P1569_1MCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P1569_1MDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("P1569_1MId");

                    b.ToTable("P1569_1Ms");
                });

            modelBuilder.Entity("SmallStructuresTakeOffs.Models.SD630Headwall", b =>
                {
                    b.Property<int>("SD630HeadwallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HWCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PipeNo")
                        .HasColumnType("int");

                    b.Property<decimal>("RebNo4Purch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RebNo4Req")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SD630Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SD630_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_E")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_G")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_I_D")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SD630_L")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThisHeadwall")
                        .HasColumnType("int");

                    b.HasKey("SD630HeadwallId");

                    b.ToTable("SD630Headwalls");
                });

            modelBuilder.Entity("SmallStructuresTakeOffs.Models.SmallStructure", b =>
                {
                    b.Property<int>("SmStId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HWcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThisStructure")
                        .HasColumnType("int");

                    b.HasKey("SmStId");

                    b.ToTable("SmallStructures");
                });
#pragma warning restore 612, 618
        }
    }
}
